issuer: https://token.actions.githubusercontent.com
subject_pattern: repo:wolfi-dev/advisories:ref:refs/heads/main
claim_pattern:
  workflow_ref: wolfi-dev/advisories/.github/workflows/auto-review-merge.yaml@refs/heads/main

# enable auto merge
permissions:
  contents: write
  pull_requests: write
  workflows: write
