issuer: https://accounts.google.com

# staging-images: cve-detection-sa@staging-images-183e.iam.gserviceaccount.com (108595486951512447790)
# prod-images: cve-detection-sa@prod-images-c6e5.iam.gserviceaccount.com (107176869706106619885)
subject_pattern: "(108595486951512447790|107176869706106619885)"

permissions:
  pull_requests: write
  contents: write
  workflows: write
